plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
}

android {
    namespace "com.shilpakala.artisan"
    compileSdk 35

    defaultConfig {
        applicationId "com.shilpakala.artisan"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    dependencies {
        implementation platform("com.google.firebase:firebase-bom:34.13.0")
        implementation "com.google.firebase:firebase-analytics"
        implementation "com.google.firebase:firebase-auth"
        implementation "com.google.firebase:firebase-firestore"
    }
}
